USE [lava]
GO

DROP SCHEMA IF EXISTS lava;
GO

CREATE SCHEMA lava;
GO

GRANT ALTER, SELECT, INSERT, UPDATE, DELETE ON SCHEMA::lava TO ${DB_LAVA_USER};
ALTER AUTHORIZATION ON SCHEMA::lava TO ${DB_LAVA_USER};
GO
