#!/bin/bash

# Custom entry point script for MySQL container to setup SSL.

# If you change this then postgresql.conf will need to change also.
[ "$SSL_DIR" == "" ] && SSL_DIR=/run/mysqld/ssl
CN="${HOST_CN-localhost}"

set -e
set -x

mkdir -p "$SSL_DIR"
chown mysql:mysql "$SSL_DIR"
chmod 700 "$SSL_DIR"

# Create a self-signed cert for the database
openssl req -new -x509 -days 365 -nodes -batch -subject \
    -out "${SSL_DIR}/server.crt" \
    -keyout "${SSL_DIR}/server.key" \
    -subj "/CN=${CN}"
chown mysql:mysql "${SSL_DIR}/server.crt" "${SSL_DIR}/server.key"
chmod 600 "${SSL_DIR}/server.key"

# Export the cert to a host mounted volume
cp "${SSL_DIR}/server.crt" /mysql

# Create a config file to active SSL.
cat > /etc/mysql/conf.d/ssl.cnf <<!
# Auto-generated by $0

[mysqld]
ssl-cert=${SSL_DIR}/server.crt
ssl-key=${SSL_DIR}/server.key
!

# Hand off to the standard mysql image entrypoint
exec docker-entrypoint.sh "$@"
