#!/bin/bash

# Custom entry point script for PostgreSQL container to setup SSL.

# If you change this then postgresql.conf will need to change also.
[ "$SSL_DIR" == "" ] && SSL_DIR=/run/postgresql/ssl
CN="${HOST_CN-localhost}"

set -e

mkdir -p "$SSL_DIR"
chown postgres:postgres "$SSL_DIR"
chmod 700 "$SSL_DIR"

# Create a self-signed cert for the database
openssl req -new -x509 -days 365 -nodes -batch -subject \
    -out "${SSL_DIR}/server.crt" \
    -keyout "${SSL_DIR}/server.key" \
    -subj "/CN=${CN}"
chown postgres:postgres "${SSL_DIR}/server.crt" "${SSL_DIR}/server.key"
chmod 600 "${SSL_DIR}/server.key"

# Export the cert to a host mounted volume
cp "${SSL_DIR}/server.crt" /postgres

# Create a little config file extension. This must already be referenced in
# postgresql.conf with an include_dir.
cat > /run/postgresql/ssl.conf <<!
# Auto-generated by $0

ssl = on
ssl_cert_file = '${SSL_DIR}/server.crt'
ssl_key_file = '${SSL_DIR}/server.key'
!

# Hand off to the standard postgres image entrypoint
exec docker-entrypoint.sh "$@"
